---
roles:
  master_latest:
    provisioners:
      - type: pe_bootstrap
        role: :master
        #version: '2016.2.1'
        download_root: "http://enterprise.delivery.puppetlabs.net/2017.2/ci-ready"
        version_file: 'http://getpe.delivery.puppetlabs.net/latest/2017.2'

  agent_latest:
    provisioners:
      - type: pe_agent
        #version: '2016.2.0'
        master: 'puppet-master-centos'
        download_root: "http://enterprise.delivery.puppetlabs.net/2017.2/ci-ready"
        version_file: 'http://getpe.delivery.puppetlabs.net/latest/2017.2'

